use_frameworks!

platform :ios, '11.0'

target 'InnovattiaPayments_Example' do
  pod 'InnovattiaPayments', :path => '../'
  pod 'SrPago-Ecommerce'
  pod 'DropDown'

  target 'InnovattiaPayments_Tests' do
    inherit! :search_paths

    
  end
end
